### ISSUE TITLE
Codify the WHO Data Set as a JSON Table Schema

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-datamodel#1]
In our ideal model, a `trial` in Open Trials should at least conform with the [WHO Trial Registration Data Set (TRDS)](http://www.who.int/ictrp/network/trds/en/). The WHO Data Set defines a minimum amount of information that a trial register should hold.

# Tasks

* [x] Take the titles and descriptions of TRDS and implement as a [JSON Table Schema](http://dataprotocols.org/json-table-schema/)
* [x] Save the schema in this repository under `external/schemas/who`
  * [x] As a directory called `trds`
  * [x] With the schema in a file called `trds.json`
  * [x] With a `README.md` that attributes the schema to WHO and links to the source of the information (http://www.who.int/ictrp/network/trds/en/)
