### ISSUE TITLE
Asses data model in relation to clinicaltrials.gov data

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-datamodel#3]
# Tasks

* [x] Document differences between ideal model and clinicaltrials.gov data
* [x] Suggest approaches to reconcile
  * [x] Be aware that we clearly do not expect a normalised data model, so not everything needed to be treated in this fashion. We expect lots of messy/inconsistent data and our final data model will reflect this
* [x] Write up as comments in this thread, and them we'll go from there to creating other tasks

**Comment by roll** [comment]
@pwalsh @danfowler 

Please take a look - https://github.com/okfn/opentrials-datamodel/wiki/clinicaltrials.gov#comparison-to-ideal-data-model - I've wrote a few lines. But it looks like we do not have to spend many time on it before we've got other datasets. I suppose we will change our ideal data model a lot later.

**Comment by pwalsh** [comment]
@roll good stuff. Yes, we'll come back to it properly when we have data from another 2 registers.

**Comment by pwalsh** [comment]
FIXED.
